package cn.ucai.fulishop.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.ucai.fulishop.db.User;
import cn.ucai.fulishop.db.FootPrint;

import cn.ucai.fulishop.db.UserDao;
import cn.ucai.fulishop.db.FootPrintDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig footPrintDaoConfig;

    private final UserDao userDao;
    private final FootPrintDao footPrintDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        footPrintDaoConfig = daoConfigMap.get(FootPrintDao.class).clone();
        footPrintDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        footPrintDao = new FootPrintDao(footPrintDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(FootPrint.class, footPrintDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        footPrintDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FootPrintDao getFootPrintDao() {
        return footPrintDao;
    }

}
