package cn.ucai.fulishop.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.ucai.fulishop.db.FootPrint;
import cn.ucai.fulishop.db.User;

import cn.ucai.fulishop.db.FootPrintDao;
import cn.ucai.fulishop.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig footPrintDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FootPrintDao footPrintDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        footPrintDaoConfig = daoConfigMap.get(FootPrintDao.class).clone();
        footPrintDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        footPrintDao = new FootPrintDao(footPrintDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(FootPrint.class, footPrintDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        footPrintDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FootPrintDao getFootPrintDao() {
        return footPrintDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
